<div class="pageContent">
	<table class="table" width="100%"  layoutH="45" border='1'>
		<thead>
			<tr>
			    <th width="25">&nbsp;</th>
			    <th width="40">编号</th>
			    <th align='center'>分类名称</th>
				<th width="80" align='center'>分类级别</th>
				<th width="80" align='center'>子分类数量</th>
				<th width="80" align='center'>文章数量</th>
				<th width="80" align='center'>分类状态</th>
			</tr>
		</thead>
		<tbody>
		     <?php foreach ($articleSortList as $articleSort):?>
	            <tr target="id" rel="<?php echo $articleSort['id']?>">
	                <td>
	                   <?php if($articleSort['right_number'] - $articleSort['left_number']==1):?>
	                      <input type='radio'  name='article' value="{article_sort_id:'<?php echo $articleSort['id'];?>',article_sort_name:'<?php echo $articleSort['name'];?>'}" />
	                   <?php else:?>
	                      &nbsp;
	                   <?php endif;?>
	                </td>
	                <td align='center'><?php echo $articleSort['id'];?></td>
	            	<td align='left'>
	                   <?php if($articleSort['children_count']>0):?>
	                      <div  class="folder" style="margin-left:<?php echo $articleSort['margin_left']?>px;"></div>
	                   <?php elseif($articleSort['children_count']==0):?>
	                      <div  class="file"   style="margin-left:<?php echo $articleSort['margin_left']?>px;"></div>
	                   <?php endif;?>
	                   <span class='item'><?php echo $articleSort['name']?></span>
	                </td>
				    <td align='center'><?php echo $articleSort['level'];?></td>
	                <td align="center"><?php echo $articleSort['children_count'];?></td>
	                <td align='center'><?php echo $articleSort['article_count'];?></td>
	                <td align='center'><?php echo $articleSort['status']?></td>
	            </tr>
	        <?php endforeach;?>
			</tbody>
			</table>
			<table>
		    <tr>
		       <td ><input type="button" multLookup="article" warn="请选择一个文章分类"  value='确认选择' /></td>
		    </tr>
			</table>
		
	
</div><!-- pageContent end -->