<table id='serviceList' cellspacing='0' cellpadding='0'  border='1'>
<thead>
   <tr>
      <th colspan='4'>多种渠道为您解决设备安装与使用过程中出现的问题</th>
   </tr>
</thead>
<tbody>
   <tr> 
      <td><a  href=tencent://message/?uin=2452926562&Site=&Menu=yes><div id='onlineService' class='serviceItem'>
      
      
          </div></a>
      </td>
      <td><div id='serviceHotline' class='serviceItem'>
      
      
          </div>
      </td>
      <td><a href="<?php echo $this->url('help',array('controller'=>'article','action'=>'index'));?>" ><div id='documentCenter' class='serviceItem'>
      
      
          </div></a>
      </td>
      <td><div id='everydayProgress' class='serviceItem'>
      
      
          </div>
      </td>
   </tr>
</tbody>
</table>


<table class='articleCollection' border='0'>
	<thead>
        <tr>
            <th colspan='4'>设备安装说明<span class='details'>从零开始，学习设备的安装</span></th>
        </tr>
	</thead>
	<tbody>
		<tr>
	        <td><div class='articleItem'><div class='icon wrench'></div>mars录播编码器</div></td>
	        <td><div class='articleItem'><div class='icon wrench'></div>saturn高清解码器</div></td>
	        <td><div class='articleItem'><div class='icon wrench'></div>venus高清分割/导播器</div></td>
	        <td><div class='articleItem'><div class='icon wrench'></div>moon音频处理器</div></td>
	    </tr>
	    <tr>
	        <td><div class='articleItem'><div class='icon wrench'></div>图像识别全自动跟踪机</div></td>
	        <td><div class='articleItem'><div class='icon wrench'></div>无线便携式录播</div></td>
	        <td><div class='articleItem'><div class='icon wrench'></div>C#录播平台</div></td>
	        <td><div class='articleItem'><div class='icon wrench'></div>PHP资源平台</div></td>
	    </tr>
	</tbody>
</table>

<table class='articleCollection' border='0'>
	<thead>
        <tr>
            <th colspan='4'>设备使用与调试说明<span class='details'>易学易用，排除不求人</span></th>
        </tr>
	</thead>
	<tbody>
		<tr>
	        <td><div class='articleItem'><div class='icon questionMark'></div>mars录播编码器</div></td>
	        <td><div class='articleItem'><div class='icon questionMark'></div>saturn高清解码器</div></td>
	        <td><div class='articleItem'><div class='icon questionMark'></div>venus高清分割/导播器</div></td>
	        <td><div class='articleItem'><div class='icon questionMark'></div>moon音频处理器</div></td>
	    </tr>
	</tbody>
</table>

<table class='articleCollection' border='0'>
	<thead>
        <tr>
            <th colspan='4'>设备性能调优<span class='details'>全面细致的了解产品的每个细节，全面提升产品的使用性能</span></th>
        </tr>
	</thead>
	<tbody>
		<tr>
	        <td><div class='articleItem'><div class='icon handbook'></div>mars录播编码器</div></td>
	        <td><div class='articleItem'><div class='icon handbook'></div>saturn高清解码器</div></td>
	        <td><div class='articleItem'><div class='icon handbook'></div>venus高清分割/导播器</div></td>
	        <td><div class='articleItem'><div class='icon handbook'></div>moon音频处理器</div></td>
	    </tr>
	</tbody>
</table>





