<div class="header search"> 
	<form id="search" action="<?php echo $this->url('help',array('controller'=>'article','action'=>'showSearchList'))?>" method="post"  >
		<table class="searchContent" cellpadding='0' cellspacing='0'>
			<tr>
				<td width='320'><input type="text"	name="keywords" class="searchvalue" /></td>
				<td><input type="submit" class="searchbutton" value="&nbsp;" /></td>
			</tr>
		</table>
	</form>
</div>