<div class="Breadcrumbs">
	您的位置：	
</div>
<div class="articleList">
	<table border='0' width='95%' cellspacing='0' cellspacing='0'>
	<thead>
		<tr>
  			<th colspan='3' align='left'><?php echo $title?></th>
		</tr>
	</thead>
	<tbody>
	<?php foreach($paginator as $article):?>
   	<tr>
    	 <td>
    		 <a target="_blank" href="<?php echo $this->url('help',array('controller'=>'article','action'=>'showArticleContent','id'=>$article->id))?>" >
     			<?php echo $article->title;?>
     	 	</a>
     	</td>
     	<td width='100'  align='center'><?php echo $article->hits;?></td>
     	<td width='80' align='center'><span><?php echo substr($article->add_time,0,10);?></span></td>
  	 </tr>
	<?php endforeach;?>
	</tbody>
	</table>
</div><!-- articleList end -->
<?php 
if (!isset($data)){
	echo  $this->paginationControl($this->paginator,'Sliding','partial/paginator',array('route'=>'help','controller'=>'article','action'=>'showLatestArticle')); 
}elseif($data['flag'] == 'sortId'){
	echo  $this->paginationControl($this->paginator,'Sliding','partial/paginator',array('route'=>'help','controller'=>'article','action'=>'showArticleList','data'=>$data['data']));
}elseif ($data['flag'] == 'keywords'){
	echo  $this->paginationControl($this->paginator,'Sliding','partial/paginator',array('route'=>'help','controller'=>'article','action'=>'showSearchList','data'=>$data['data']));
}

?>




<script type="text/javascript">
$(document).ready(function(){
	paginatorEnv();
});
</script>