<div class="pageContent">
	<div class="panelBar">
		<ul class="toolBar">
			<li><a class="add" href="<?php echo $this->url('system',array('controller'=>'role','action'=>'showRoleAdd'));?>" target="navTab" title="角色添加" rel='showRoleAdd'><span>添加角色</span></a></li>
			<li><a class="delete" href="<?php echo $this->url('system',array('controller'=>'role','action'=>'checkRoleDelete'));?>?id={id}" target="ajaxTodo" title="确定要删除吗?"><span>删除角色</span></a></li>
			<li><a class="edit" href="<?php echo $this->url('system',array('controller'=>'role','action'=>'showRoleEdit'));?>?id={id}" target="navTab" title="编辑角色" rel={id}><span>修改角色</span></a></li>
			<li><a class="edit" href="<?php echo $this->url('system',array('controller'=>'role','action'=>'showRolePermissionEdit'));?>?id={id}" target="navTab" title="编辑角色权限" rel={id} ><span>编辑角色权限</span></a></li>
		</ul>
	</div>
	<table class="table" width="100%"  layoutH="138" targetType="navTab">
		<thead>
			<tr>
				<th width="40"  align='center'>编号</th>
				<th align='center'>角色名称</th>
				<th width="80"  align='center'>角色级别</th>
				<th width="80"  align='center'>子角色数量</th>
				<th width="80"  align='center'>用户数量</th>
				<th width="400" align='center'>角色描述</th>
				<th width="80"  align='center'>用户状态</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($roleList as $role):?>
		<tr target="id" rel="<?php echo $role['id'];?>">
		    <td><?php echo $role['id'];?></td>
			<td>
				<?php if($role['children_count']>0):?>
	                 <div  class="folder" style="margin-left:<?php echo $role['margin_left']?>px;"></div>
	            <?php elseif($role['children_count']==0):?>
	                 <div  class="file"   style="margin-left:<?php echo $role['margin_left']?>px;"></div>
	            <?php endif;?>
				<span class='item'><?php echo $role['name']?></span>
			</td>
			<td><?php echo $role['level'];?></td>
			<td><?php echo $role['children_count'];?></td>
			<td><?php echo $role['user_count'];?></td>
			<td><?php echo $role['description'];?></td>
			<td><?php echo $role['status'];?></td>
		</tr>
		<?php endforeach;?>
		</tbody>
	</table>
</div>