<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=7" />
<?php echo $this->headTitle();?>
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/theme/favicon.ico'))
                ->appendStylesheet($this->basePath() . '/theme/default/style.css')                   
                ->appendStylesheet($this->basePath() . '/theme/core.css')
                ->appendStylesheet($this->basePath() . '/theme/print.css',"print")
                ->appendStylesheet($this->basePath() . '/theme/self.css')
                ->appendStylesheet($this->basePath() . '/plugin/uploadify/css/uploadify.css')
			    ->appendStylesheet($this->basePath() . '/theme/ieHack.css',array('conditional' => 'IF IE',))

?>

<?php     echo $this->headScript()->appendFile($this->basePath() . '/js/compatible/speedup.js', 'text/javascript', array('conditional' => 'lt IE 9',))
								  ->appendFile($this->basePath() . '/js/compatible/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
								  ->appendFile($this->basePath() . '/js/compatible/swfobject.js')
								  ->appendFile($this->basePath() . '/js/org/jquery/jquery-1.7.2.min.js')
                                  ->appendFile($this->basePath() . '/js/org/jquery/jquery.cookie.js')
                                  ->appendFile($this->basePath() . '/js/org/jquery/jquery.validate.js')
								  ->appendFile($this->basePath() . '/js/org/jquery/jquery.bgiframe.js')
								  ->appendFile($this->basePath() . '/plugin/xheditor/xheditor-1.1.14-zh-cn.min.js')
								  ->appendFile($this->basePath() . '/plugin/uploadify/scripts/jquery.uploadify.js')
								  ->appendFile($this->basePath() . '/plugin/dwz/dwz.min.gzjs')
								  ->appendFile($this->basePath() . '/plugin/dwz/dwz.regional.zh.js')
								  ->appendFile($this->basePath() . '/plugin/dwz/dwz.unlimitedCombox.js')
								  ->appendFile($this->basePath() . '/plugin/dwz/dwz.report.js')
?>
<script type="text/javascript">
$(function(){
	DWZ.init("<?php echo $this->basePath().'/plugin/dwz/dwz.frag.xml'?>", {
		loginUrl:"login_dialog.html", loginTitle:"登录",	// 弹出登录对话框
		statusCode:{ok:200, error:300, timeout:301}, //【可选】
		pageInfo:{pageNum:"pageNum", numPerPage:"numPerPage", orderField:"orderField", orderDirection:"orderDirection"}, //【可选】
		debug:false,	// 调试模式 【true|false】
		callback:function(){
			initEnv();
		}
	});
});
</script>
</head>
<body scroll="no">
	<div id="layout">
		<div id="header">
			<div class="headerNav">
				<a class="logo" href="http://www.etah-tech.com">标志</a>
				<ul class="nav">
					<li><a href='javascript::void(0)'>欢迎您，<?php echo $realname?></a></li>
					<li><a target="dialog" mask='true' title="修改密码" width="300" height="120"  href="<?php echo $this->url('application',array('controller'=>'index','action'=>'showPasswordChange'))?>">修改密码</a></li>
					<li><a href="<?php echo $this->url('application',array('controller'=>'index','action'=>'logout'))?>">退出</a></li>
				</ul>
			</div>
			<div id="navMenu">
				<?php echo $this->navigation()->Admin()->renderNav();?>
			</div><!-- navMenu end -->
		</div><!-- header end -->

		<div id="leftside">
			<div id="sidebar_s">
				<div class="collapse">
					<div class="toggleCollapse"><div></div></div>
				</div>
			</div>
			<div id="sidebar">
				<?php echo $this->navigation()->Admin()->renderSidebar(); ?>
			</div><!-- sidebar -->
		</div>
		<div id="container">
			<div id="navTab" class="tabsPage">
				<div class="tabsPageHeader">
					<div class="tabsPageHeaderContent"><!-- 显示左右控制时添加 class="tabsPageHeaderMargin" -->
						<ul class="navTab-tab">
							<li tabid="main" class="main"><a href="javascript:;"><span><span class="home_icon">我的主页</span></span></a></li>
						</ul>
					</div>
					<div class="tabsLeft">left</div><!-- 禁用只需要添加一个样式 class="tabsLeft tabsLeftDisabled" -->
					<div class="tabsRight">right</div><!-- 禁用只需要添加一个样式 class="tabsRight tabsRightDisabled" -->
					<div class="tabsMore">more</div>
				</div>
				<ul class="tabsMoreList">
					<li><a href="javascript:;">我的主页</a></li>
				</ul>
				<div class="navTab-panel tabsPageContent layoutBox">
					<div class="page bedpeople">
						<?php echo $contnet;?>
						
					</div>
					
				</div>
			</div>
		</div>

	</div>
</body>
</html>