<form action="<?php echo $this->url('application',array('controller'=>'index','action'=>'checkPasswordChange'));?>"  class="pageForm required-validate" onsubmit="return validateCallback(this);" method="post">
	<table>
		<tr>
			<td width='80'><label>密码：</label></td>
			<td><input type="password" name="password" /></td>
		</tr>
		<tr>
			<td><label>确认密码：</label></td>
			<td><input type="password" name="confirmPassword" /></td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>
				<input type="submit" value="提交" />
			    <input type="reset" value="重置" />
			</td>
		</tr>
	</table>
</form>